# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'todo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MagicalRecord'

  # Pods for todo

  target 'todoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
